// Generated by CoffeeScript 1.6.2
(function() {
  var Q;

  Q = require('q');

  exports.wait = function*(callback) {
    var deffered;

    deffered = Q.defer();
    callback.call(this, function(err, result) {
      if (err) {
        return deffered.fail(err);
      } else {
        return deffered.resolve(result);
      }
    });
    yield deffered.promise;
  };

}).call(this);
