// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter;

  EventEmitter = require('events').EventEmitter;

  EventEmitter.prototype.wait = function(success, failure) {
    var deffered;

    if (success == null) {
      success = 'success';
    }
    if (failure == null) {
      failure = 'failure';
    }
    deffered = Q.defer();
    this.on(success, function() {
      return deffered.resolve.apply(deffered, arguments);
    });
    this.on(failure, function() {
      return deffered.fail.apply(deffered, arguments);
    });
    return yield deffered.promise;
  };

}).call(this);
