// Generated by CoffeeScript 1.6.2
(function() {
  var Fiber, coffee, compile, context, fs, path, view;

  Fiber = require('fibers');

  path = require('path');

  fs = require('fs');

  context = require('../context');

  coffee = require('coffee-script');

  compile = function(path) {
    var fiber;

    fiber = Fiber.current;
    fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        fiber.throwInto(err);
      }
      return fiber.run(coffee.compile(data));
    });
    return Fiber["yield"]();
  };

  view = function(name) {
    this.contentType = 'text/javascript';
    path = this.resolve(name);
    return compile(path);
  };

  context.include({
    coffee: view
  });

  module.exports = compile;

}).call(this);
