// Generated by CoffeeScript 1.6.2
(function() {
  var Q, coffee, compile, context, fs, path, view;

  Q = require('q');

  path = require('path');

  fs = require('fs');

  context = require('../context');

  coffee = require('coffee-script');

  compile = function(path) {
    var deffered;

    deffered = Q.defer();
    fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        return deffered.fail(err);
      }
      return deffered.resolve(coffee.compile(data));
    });
    return deffered.promise;
  };

  view = function(name) {
    this.contentType = 'text/javascript';
    path = this.resolve(name);
    return compile(path);
  };

  context.include({
    coffee: view
  });

  module.exports = compile;

}).call(this);
