// Generated by CoffeeScript 1.6.2
(function() {
  var Q, compile, context, eco, fs, path, view;

  Q = require('q');

  path = require('path');

  fs = require('fs');

  context = require('../context');

  eco = require('eco');

  compile = function(path, context) {
    var deffered;

    deffered = Q.defer();
    fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        return deffered.fail(err);
      }
      return deffered.resolve(eco.render(data, context));
    });
    return deffered.promise;
  };

  view = function(name, options) {
    var layout, result;

    if (options == null) {
      options = {};
    }
    path = this.resolve(name);
    result = compile(path, this);
    layout = options.layout;
    if (layout == null) {
      layout = this.settings.layout;
    }
    if (layout) {
      result = compile(layout, {
        body: result
      });
    }
    return result;
  };

  context.include({
    eco: view
  });

  module.exports = compile;

}).call(this);
