// Generated by CoffeeScript 1.6.2
(function() {
  var Q, compile, context, ejs, fs, path, view;

  Q = require('q');

  path = require('path');

  fs = require('fs');

  context = require('../context');

  ejs = require('ejs');

  compile = function(path, context) {
    var deffered;

    deffered = Q.defer();
    fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        return deffered.fail(err);
      }
      return deffered.resolve(ejs.render(data, context));
    });
    return deffered.promise;
  };

  view = function(name) {
    path = this.resolve(name);
    return compile(path, this);
  };

  context.include({
    ejs: view
  });

  module.exports = compile;

}).call(this);
