// Generated by CoffeeScript 1.6.2
(function() {
  var Q, compile, context, fs, less, path, view, _base;

  Q = require('q');

  path = require('path');

  fs = require('fs');

  context = require('../context');

  less = require('less');

  compile = function(path) {
    var deffered;

    deffered = Q.defer();
    fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        return deffered.fail(err);
      }
      return less.render(data, function(err, css) {
        if (err) {
          return deffered.fail(err);
        }
        return deffered.resolve(css);
      });
    });
    return deffered.promise;
  };

  view = function(name) {
    this.contentType = 'text/css';
    path = this.resolve(name);
    return compile(path);
  };

  (_base = require.extensions)['.less'] || (_base['.less'] = function(module, filename) {});

  context.include({
    less: view
  });

  module.exports = compile;

}).call(this);
