// Generated by CoffeeScript 1.6.2
(function() {
  var Q, compile, context, fs, path, stylus, view, _base;

  Q = require('q');

  path = require('path');

  fs = require('fs');

  context = require('../context');

  stylus = require('stylus');

  compile = function(path, context) {
    var deffered;

    deffered = Q.defer();
    fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        return deffered.fail(err);
      }
      return stylus.render(data, {
        filename: path
      }, function(err, css) {
        if (err) {
          return deffered.fail(err);
        }
        return deffered.resolve(css);
      });
    });
    return deffered.promise;
  };

  view = function(name) {
    this.contentType = 'text/css';
    path = this.resolve(name);
    return compile(path);
  };

  (_base = require.extensions)['.styl'] || (_base['.styl'] = function(module, filename) {});

  context.include({
    stylus: view,
    styl: view
  });

  module.exports = compile;

}).call(this);
